### ISSUE TITLE
Error in your Bat file

### ISSUE THREAD

**Issue by Fasto5** [TBR-Development/RAMMap-Task-Scheduler#1]
Hi there, I think I found an error in your .bat file. 

I couldn't get the options B-E to work (it returns an ERROR). 

So I looked at the coding and realised the only working option (Option A) ended in HRESULT

However the other options ended in HRESULTHRESULT

I 'hoped' for it to be a typo and changed it to just HRESULT and that BOOM! it works!

Thanks for making this bat file! Empty working sets fixes my issue on w11

**Comment by PhantomNimbi** [comment]
Yo, I'm glad you got that fixed. Sorry about the typo. I'll get that fixed on our end as well.


Thanks for letting me know about it.

**Comment by PhantomNimbi** [comment]
Aaand fixed. Should be good on our end now too.
